"""Regression coverage for clip-detail panel content truncation at narrow
widths (issue #83).

PreviewPanel._title (a CTkLabel showing the selected clip's title) had no
wraplength, so a long title simply rendered past the label's own bounds and
was visually clipped instead of wrapping -- reproduced via real winfo_width()
measurements and confirmed visually via a real GUI screenshot during manual
investigation (not committed here; see the PR description). It is most
noticeable at compact/standard widths, where the panel itself is narrower,
but the same missing-wraplength defect is present at any width where a title
happens to be longer than the panel.

PreviewPanel now recomputes self._title's wraplength from the title frame's
actual current width on every resize (see _on_title_frame_configure in
preview.py), converting from the widget's physical (DPI-scaled) winfo_width()
back to the logical units CTkLabel.configure(wraplength=...) expects before
CustomTkinter re-applies its own scaling -- passing the physical value
straight through double-scales it, silently loosening the wrap boundary
past the panel's real on-screen width (caught during this fix's own
development, not merely theoretical).

Uses only synthetic clip content; no real clipboard or profile data.
"""

from __future__ import annotations

from unittest.mock import patch

import pytest

from cache_vault.core.models import CLASS_LINK, CLASS_PLAIN, CONTENT_IMAGE, CONTENT_TEXT, Clip
from cache_vault.core.storage import FILTER_ALL
from cache_vault.ui.shell import CacheVaultApp

LONG_TITLE_SOURCE = "synthetic long word " * 40
LONG_UNBROKEN_TOKEN = "synthetic-unbroken-token-" + ("x" * 120)


@pytest.fixture
def app(tk_root, vault):
    app = CacheVaultApp(vault=vault)
    yield app
    app.destroy()


def _select_clip(app, clip) -> None:
    # _on_clip_select is the real production selection path (what a click on
    # a clip row actually invokes) -- it both shows the clip in the preview
    # AND calls _update_inspector_visibility(), which is what actually grids
    # or place()s the panel. Manually setting _selected_clip_id and calling
    # refresh()/preview.show() directly (an earlier version of this helper)
    # skips _update_inspector_visibility() entirely, leaving the panel
    # unmapped despite a selection -- caught by the mapped-state assertions
    # below, not a real defect in the app.
    #
    # update_idletasks (not update) throughout -- see _set_layout_mode's
    # docstring: a plain update() can drain a real, now-overdue resize
    # <Configure> job and silently flip the mode this test just forced.
    app._navigate_screen(FILTER_ALL)
    app.update_idletasks()
    if app._resize_job:
        app.after_cancel(app._resize_job)
        app._resize_job = None
    app._on_clip_select(clip)
    app.update_idletasks()
    if app._resize_job:
        app.after_cancel(app._resize_job)
        app._resize_job = None


def _set_layout_mode(app, mode: str, width: int) -> None:
    """Force a layout mode deterministically, the same way
    test_pr_a_layout.py's test_breakpoint_resolution does (mocking
    winfo_width rather than relying on real, DPI-scaled window geometry).

    Cancels any pending _resize_job both before and after the forced call:
    a real <Configure> event -- generated by this app's own window-manager
    geometry settling, which can still be pending by the time a test body
    runs, well after construction -- schedules a genuine self.after(150,
    _handle_resize_debounced) job via _on_window_configure. If enough
    wall-clock time has already elapsed (routine given fixture/import
    overhead), a plain app.update() will drain that queue and execute the
    now-due job for real, silently overwriting the forced mode with
    whatever this window's actual current size computes to. update_idletasks
    (not update) is used deliberately below: it recalculates geometry so
    winfo_width()/winfo_reqwidth() on children are current, without
    processing the event queue that could re-trigger a real resize.
    """
    if app._resize_job:
        app.after_cancel(app._resize_job)
        app._resize_job = None
    with patch.object(app, "winfo_width", return_value=width):
        app._handle_resize_debounced()
    if app._resize_job:
        app.after_cancel(app._resize_job)
        app._resize_job = None
    app.update_idletasks()
    if app._resize_job:
        app.after_cancel(app._resize_job)
        app._resize_job = None
    assert app._current_layout_mode == mode, (
        f"test setup requires {mode!r} at width={width}, got {app._current_layout_mode!r}"
    )


def _title_fits_within_frame(app) -> bool:
    """The title's rendered (post-wrap) width must never exceed its own
    allotted area -- the frame's width minus the close button sharing it."""
    preview = app._preview
    title, frame, close_btn = preview._title, preview._title_frame, preview._close_btn
    app.update_idletasks()
    frame_w = frame.winfo_width()
    close_w = close_btn.winfo_width() if close_btn.winfo_ismapped() else 0
    return title.winfo_reqwidth() <= frame_w - close_w + 6


def _make_clip(content: str, *, preview: str, content_type: str = CONTENT_TEXT,
                classification: str = CLASS_PLAIN) -> Clip:
    return Clip(content=content, preview=preview, content_type=content_type,
                classification=classification, source_app="test")


@pytest.mark.parametrize("width,mode", [
    (900, "compact"),
    (1149, "compact"),
    (1150, "standard"),
    (1499, "standard"),
    (1500, "wide"),
])
def test_title_bounds_within_parent_at_every_breakpoint(app, vault, width, mode):
    """1: the detail panel's title content bounds remain within its parent
    at every layout-mode breakpoint, including immediately below/above the
    compact-toolbar threshold and at the minimum supported width."""
    clip = _make_clip(LONG_TITLE_SOURCE, preview=LONG_TITLE_SOURCE)
    vault.storage.add_clip(clip)
    _set_layout_mode(app, mode, width)
    _select_clip(app, clip)
    assert _title_fits_within_frame(app), (
        f"title overflowed its own frame at width={width} mode={mode}"
    )


def test_preview_textbox_remains_visible_and_usable(app, vault):
    """2: the preview textbox remains visible and usable at minimum width."""
    clip = _make_clip(LONG_TITLE_SOURCE, preview="short")
    vault.storage.add_clip(clip)
    _set_layout_mode(app, "compact", 900)
    _select_clip(app, clip)
    body = app._preview._body
    assert body.winfo_ismapped()
    assert body.winfo_width() > 0
    assert body._textbox.cget("state") == "disabled"  # read-only preview, still rendered


def test_action_row_remains_fully_reachable(app, vault):
    """3: the action row (primary + secondary buttons) remains fully
    reachable at minimum width -- mapped and non-zero size."""
    clip = _make_clip("short body", preview="short")
    vault.storage.add_clip(clip)
    _set_layout_mode(app, "compact", 900)
    _select_clip(app, clip)
    buttons_frame = app._preview._buttons
    assert buttons_frame.winfo_ismapped()
    children = buttons_frame.winfo_children()
    assert children, "expected at least the primary action button"
    for child in children:
        assert child.winfo_width() > 0 or not child.winfo_ismapped()


def test_long_text_wraps_without_horizontal_clipping(app, vault):
    """4: long synthetic text in the body wraps (word-wrap) and does not
    force horizontal clipping -- an unbreakable single token may still
    engage the textbox's own horizontal scrollbar, which is scrollable
    access, not unreachable/clipped content."""
    clip = _make_clip(LONG_TITLE_SOURCE, preview="short")
    vault.storage.add_clip(clip)
    _set_layout_mode(app, "compact", 900)
    _select_clip(app, clip)
    body = app._preview._body
    # word-wrapped multi-line content never needs the x-scrollbar
    assert not body._x_scrollbar.winfo_ismapped()


def test_long_unbroken_token_remains_reachable_via_scroll(app, vault):
    clip = _make_clip(LONG_UNBROKEN_TOKEN, preview="short")
    vault.storage.add_clip(clip)
    _set_layout_mode(app, "compact", 900)
    _select_clip(app, clip)
    body = app._preview._body
    # An unbreakable token wider than the textbox engages the horizontal
    # scrollbar rather than being silently clipped with no way to reach it.
    if body._textbox.xview() != (0.0, 1.0):
        assert body._x_scrollbar.winfo_ismapped()


@pytest.mark.parametrize("content_type,classification,content", [
    (CONTENT_TEXT, CLASS_PLAIN, LONG_TITLE_SOURCE),
    (CONTENT_TEXT, CLASS_LINK, "https://example.com/" + "segment/" * 20),
    (CONTENT_IMAGE, CLASS_PLAIN, "unused-for-image"),
])
def test_clip_types_do_not_overflow_at_minimum_width(app, vault, content_type, classification, content):
    """5: text, link, and image clip types do not overflow the detail panel
    at minimum width (image asset is missing in this synthetic fixture, but
    that must degrade to a message, not an overflow or a crash)."""
    clip = _make_clip(content, preview=content[:60], content_type=content_type,
                       classification=classification)
    vault.storage.add_clip(clip)
    _set_layout_mode(app, "compact", 900)
    _select_clip(app, clip)
    assert _title_fits_within_frame(app)
    preview = app._preview
    assert preview.winfo_ismapped()


@pytest.mark.parametrize("view_mode", ["cards", "grid"])
def test_cards_and_grid_produce_equivalent_containment(app, vault, view_mode):
    """6: Cards and Grid view modes produce equivalent title containment."""
    clip = _make_clip(LONG_TITLE_SOURCE, preview=LONG_TITLE_SOURCE)
    vault.storage.add_clip(clip)
    app._set_view_mode(view_mode)
    _set_layout_mode(app, "compact", 900)
    _select_clip(app, clip)
    assert _title_fits_within_frame(app)


def test_resize_transitions_update_detail_panel_correctly(app, vault):
    """7: compact, standard, and wide resize transitions each update the
    detail panel's title containment correctly, in sequence."""
    clip = _make_clip(LONG_TITLE_SOURCE, preview=LONG_TITLE_SOURCE)
    vault.storage.add_clip(clip)
    _select_clip(app, clip)
    for width, mode in [(900, "compact"), (1150, "standard"), (1600, "wide")]:
        _set_layout_mode(app, mode, width)
        app._preview._on_title_frame_configure()
        app.update_idletasks()
        assert _title_fits_within_frame(app), f"failed containment after transition to {mode}"


def test_recovery_from_minimum_to_wide_restores_layout(app, vault):
    """8: returning from minimum width to wide mode restores the intended
    layout -- the inspector is grid-managed (not the compact place() slide-
    over) and containment still holds."""
    clip = _make_clip(LONG_TITLE_SOURCE, preview=LONG_TITLE_SOURCE)
    vault.storage.add_clip(clip)
    _select_clip(app, clip)
    _set_layout_mode(app, "compact", 900)
    assert app._preview.winfo_manager() == "place"
    _set_layout_mode(app, "wide", 1600)
    assert app._preview.winfo_manager() == "grid"
    assert _title_fits_within_frame(app)


def test_navigation_away_and_back_does_not_retain_stale_narrow_state(app, vault):
    """9: navigating away from a clip and back does not retain stale
    wraplength/geometry state from a previous (narrower) width."""
    clip = _make_clip(LONG_TITLE_SOURCE, preview=LONG_TITLE_SOURCE)
    vault.storage.add_clip(clip)
    _set_layout_mode(app, "compact", 900)
    _select_clip(app, clip)
    narrow_wrap = app._preview._title.cget("wraplength")

    app._close_inspector()
    app.update_idletasks()

    _set_layout_mode(app, "wide", 1600)
    _select_clip(app, clip)
    wide_wrap = app._preview._title.cget("wraplength")

    assert wide_wrap != narrow_wrap, "wraplength must be recomputed for the new width, not stale"
    assert _title_fits_within_frame(app)


def test_toolbar_and_lifecycle_state_unaffected(app, vault):
    """10: the responsive toolbar (PR #82) and textbox lifecycle protection
    (PR #85) are unaffected by this fix -- spot-check both still behave
    normally alongside a narrow-width detail panel."""
    clip = _make_clip("short", preview="short")
    vault.storage.add_clip(clip)
    _set_layout_mode(app, "compact", 900)
    _select_clip(app, clip)
    assert app._top_more_btn.winfo_ismapped()  # compact overflow present
    assert app._control_strip is not None
    # CacheVaultTextbox lifecycle: destroying the panel's body must not leave
    # an unresolved scrollbar-check job (see test_ctk_textbox_scrollbar_teardown.py
    # for the dedicated, exhaustive coverage; this is a spot check only).
    body = app._preview._body
    job_before = body._scrollbar_check_job
    assert job_before is not None or not body.winfo_exists()
