"""Temporary pairing offer management for secure QR code mobile onboarding."""

from __future__ import annotations

import json
import secrets
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any

from .models import DEFAULT_MOBILE_PORT

PAIRING_OFFER_TTL_SECONDS = 300  # 5 minutes


@dataclass
class PairingOffer:
    token: str
    host: str
    port: int
    created_at: float
    expires_at: float
    pc_name: str = "Cache Vault Desktop"
    consumed: bool = False

    @property
    def is_expired(self) -> bool:
        return time.time() >= self.expires_at

    @property
    def is_valid(self) -> bool:
        return not self.consumed and not self.is_expired

    def to_qr_payload(self) -> str:
        """Format temporary pairing offer into QR code JSON string."""
        exp_iso = datetime.fromtimestamp(self.expires_at, tz=timezone.utc).isoformat()
        payload = {
            "v": 1,
            "host": self.host,
            "port": self.port,
            "token": self.token,
            "expires_at": exp_iso,
            "pc_name": self.pc_name,
        }
        return json.dumps(payload, separators=(",", ":"))

    def to_dict(self) -> dict[str, Any]:
        return {
            "host": self.host,
            "port": self.port,
            "token": self.token,
            "expires_at": self.expires_at,
            "pc_name": self.pc_name,
            "consumed": self.consumed,
            "expired": self.is_expired,
        }


class PairingOfferManager:
    """Manages temporary 1-time pairing offers generated by desktop for QR scanning."""

    def __init__(self, ttl_seconds: int = PAIRING_OFFER_TTL_SECONDS):
        self.ttl_seconds = ttl_seconds
        self._offers: dict[str, PairingOffer] = {}

    def create_offer(
        self,
        host: str,
        port: int = DEFAULT_MOBILE_PORT,
        pc_name: str = "Cache Vault Desktop",
    ) -> PairingOffer:
        """Generate a new 32-byte entropy temporary pairing offer."""
        token = secrets.token_urlsafe(32)
        now = time.time()
        offer = PairingOffer(
            token=token,
            host=host,
            port=port,
            created_at=now,
            expires_at=now + self.ttl_seconds,
            pc_name=pc_name,
            consumed=False,
        )
        self._offers[token] = offer
        self._cleanup()
        return offer

    def get_offer(self, token: str) -> PairingOffer | None:
        self._cleanup()
        return self._offers.get(token)

    def consume_offer(self, token: str) -> tuple[bool, str]:
        """Validate and consume a pairing offer. Returns (success, reason_if_failed)."""
        offer = self._offers.get(token)
        if offer is None:
            return False, "invalid_pairing_token"
        if offer.consumed:
            return False, "offer_already_used"
        if offer.is_expired:
            return False, "offer_expired"

        offer.consumed = True
        return True, "ok"

    def _cleanup(self) -> None:
        """Remove expired or consumed offers older than 10 minutes."""
        cutoff = time.time() - 600
        to_delete = [
            token
            for token, offer in self._offers.items()
            if offer.created_at < cutoff
        ]
        for token in to_delete:
            self._offers.pop(token, None)
